use_frameworks!
source 'https://github.com/ibroadlink/BLLibSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'BLSFamily_Example' do
  pod 'BLSFamily', :path => '../'

  target 'BLSFamily_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
